apiVersion: v1
kind: Service
metadata:
  name: go-demo
  labels:
    name: api-server
    app: go-demo
spec:
  type: NodePort
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    name: api-server
    app: go-demo
